services:
  backend:
    container_name: curelingo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - curelingo-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: curelingo-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - curelingo-network

networks:
  curelingo-network:
    driver: bridge
